### ISSUE TITLE
[bug?] DDVFA mismatch_flag should probably be false in supervised classification

### ISSUE THREAD

**Issue by hayesall** [AP6YC/AdaptiveResonance.jl#42]
(*I might be misinterpreting something, but this seemed like something that should not occur in the supervised case.*)

In rare cases, running `classify` with supervised DDVFA may return a vector containing `-1` that does not correspond to one of the labels in the original data space.

![Plot of supervised DDVFA with two Gaussians. There are three labels: 0, 1, -1; but -1 was not part of the original feature space](https://user-images.githubusercontent.com/11916674/137928746-46696041-46d6-4736-a4b9-4935bec6d38d.png)

It looks like this is caused by an interaction between `mismatch_flag` defaulted to `true`, and the similarity/`art.threshold` value:

https://github.com/AP6YC/AdaptiveResonance.jl/blob/f1227ea692643796ae3d38eb7267b0536f928688/src/ART/DDVFA.jl#L818-L822

## Reproducing

This only seems to happen ~30% of the time depending on the split of the data:

```julia
julia> DataStructures.counter(y_hat_test)
Accumulator{Int64, Int64} with 3 entries:
  0  => 304
  -1 => 2
  1  => 294
```

But here's the code I used to create the figures:

```julia
using AdaptiveResonance
using Distributions, Random
using MLDataUtils
using Plots

rng = MersenneTwister(1234)
dist1 = MvNormal([0.0, 6.0], [1.0 0.0; 0.0 1.0])
dist2 = MvNormal([4.5, 6.0], [2.0 -1.5; -1.5 2.0])

N_POINTS = 1000

X = hcat(rand(rng, dist1, N_POINTS), rand(rng, dist2, N_POINTS))
y = vcat(ones(Int64, N_POINTS), zeros(Int64, N_POINTS))

p1 = scatter(X[1,:], X[2,:], group=y, title="Original Data")

(X_train, y_train), (X_test, y_test) = stratifiedobs((X, y))

art = DDVFA()
train!(art, X_train)
y_hat_test = AdaptiveResonance.classify(art, X_test)
p2 = scatter(X_test[1,:], X_test[2,:], group=y_hat_test, title="Unsupervised DDVFA")

art = DDVFA()
train!(art, X_train, y=y_train)
y_hat_test = AdaptiveResonance.classify(art, X_test)
p3 = scatter(X_test[1,:], X_test[2,:], group=y_hat_test, title="Supervised DDVFA", xlabel="Performance: " * string(round(performance(y_hat_test, y_test); digits=3)))

plt = plot(p1, p2, p3, layout=(1, 3), legend = false, xtickfontsize=6, xguidefontsize=8, titlefont=font(8))
```

**Comment by markNZed** [comment]
i wonder if setting the argument get_bmu to true would fix this?  https://github.com/AP6YC/AdaptiveResonance.jl/blob/f1227ea692643796ae3d38eb7267b0536f928688/src/ART/DDVFA.jl#L778

**Comment by AP6YC** [comment]
Good catch @hayesall, and @markNZed is correct. The actionable item is that it is something for me to document much better considering how important of a point it is.

During inference, ART algorithms are defined to return their category belief only if the match function vigilance test is passed. Because one may still want a "best-matching-unit" (i.e., highest activated category through the activation function) for situations where you want an answer regardless of mismatch, I added a `get_bmu` to the ART implementations.

What you see in the plot is the result of "default" ART behavior. I will certainly add a blurb in the usage section of the docs, but I think that the point might merit a full page with an example such as yours. I'll link the feature that implements it.

**Comment by AP6YC** [comment]
PR #47 documents the mismatch vs. best-matching unit dynamics I mentioned above in the README and docs. My hope is that including it in the README's quickstart brings this usage to light quickly for the reader.

**Comment by AP6YC** [comment]
I'll probably only close this once I get examples with DemoCards (Issues #26 and #27) that include showing the difference with and without `get_bmu`.

**Comment by AP6YC** [comment]
PR #49 implements those `DemoCards` examples in the Examples section of the docs.
